### ISSUE TITLE
Am I able to replace the API key based in realtime?

### ISSUE THREAD

**Issue by finrojo** [dhaspden/nestjs-stripe#101]
### Question:

I am working with a client that takes payments for several different Stripe accounts and need to be able to direct the payment to different API keys based on the company the booking is being made for.

I am new to Nest so am not sure about overriding the API that is applied when my module loads.

**Comment by dhaspden** [comment]
As far as I know you can't with Typescript because the Stripe Typescript library prescribes the API version. See the `README.md`. They may have changed since I wrote this library but I'm not aware of this being possible yet. Sorry!
