### ISSUE TITLE
Iris <> Job Possibility 

### ISSUE THREAD

**Issue by brianschardt** [dhaspden/nestjs-stripe#105]
I am the founder of a VC-backed app called Iris, that allows you to connect your brokerage to enable you to share your trades with your friends and family.

Here is a quick product video: https://www.youtube.com/watch?v=kHtE-LMYxcg

We only hire super active engineers that have a history of contributing/creating prominent open source packages as these are some of the most talented people out there. 

We have the creator of the GetX package for flutter(most like and used flutter package)
We just hired the lead AI/ML engineer from TikTok 

We love what you have done to make it easier to integrate nestjs and stripe. 

Our app currently has 50k users and we can see $5 billion of orders on our platform, we are growing fast and are looking to slowly add talented engineers. 

You are probably not looking for a job right now however do you have 15 min to chat this week or next? if so here is a calendar link I would love to speak with you!

https://calendly.com/brian-iris

Thanks,
Brian Schardt

**Comment by dhaspden** [comment]
I'm very much happy in my current position, thanks though.
