### ISSUE TITLE
Support Nest v8

### ISSUE THREAD

**Issue by sidharthv96** [dhaspden/nestjs-stripe#107]
### Bug reports:

NestJS v8 upgrade throws several warnings.

```
warning " > nestjs-stripe@0.4.1" has incorrect peer dependency "@nestjs/common@^6.0.0 || ^7.0.0".
warning " > nestjs-stripe@0.4.1" has incorrect peer dependency "@nestjs/core@^6.0.0 || ^7.0.0".
warning " > nestjs-stripe@0.4.1" has incorrect peer dependency "rxjs@^6.0.0".
```

**Comment by dhaspden** [comment]
When I saw the release 8 I figured this would come up. I can probably take a look tomorrow and post a new release 👍

**Comment by Royserg** [comment]
Hi, after upgrading nest to version 8 I am facing the same error as @sidharthv96 
Is there any update related to this?

**Comment by faan11** [comment]
hi, i also need this update, are there any news about it?

**Comment by dhaspden** [comment]
Done! Thanks for waiting. You can now use version `1.0.0` for Nest 8 support.

**Comment by sidharthv96** [comment]
Thanks for the awesome work @dhaspden !!
