### ISSUE TITLE
Add useExisting syntax for configuring the module

### ISSUE THREAD

**Issue by IGassmann** [dhaspden/nestjs-stripe#34]
[Like other official Nest modules](https://docs.nestjs.com/techniques/database), it would be nice to propose the `useExisting` syntax for configuring the module.

**Comment by dhaspden** [comment]
@IGassmann thanks for the feedback.  I agree, if the framework has a way for that then we should too.  I'll take a look!

**Comment by IGassmann** [comment]
Awesome! BTW, thanks for having built this module!

**Comment by dhaspden** [comment]
I matched how the official libraries implemented this, let me know if it works as you expect it to @IGassmann.  Thanks for the feedback!

Released in v0.2.0 on npm!

**Comment by IGassmann** [comment]
It does! Good work!
