### ISSUE TITLE
apiVersion can only be set to the latest api version? Can this be set to be latestVersion or string?

### ISSUE THREAD

**Issue by ntegral** [dhaspden/nestjs-stripe#92]
apiVersion can only be set to the latest api version? Can this be set to be latestVersion or string?

**Comment by dhaspden** [comment]
@ntegral thanks for opening the issue. I have _just_ released 0.4.0. Does this solve your needs? As far as I know you can provide your own version string.

**Comment by ntegral** [comment]
The short answer is no.  Your StripeOptions extends the Stripe.StripeConfig interface and the apiVersion only accepts a type of LatestVersion which is set to "2020-03-02";  In order to use a different apiVersion the underlying library requires that I use @ts-ignore statement to use a different version. So technically, it's not the code that you've written... it's the underlying dependency code.

**Comment by dhaspden** [comment]
I see. I briefly looked into it and saw [this](https://github.com/stripe/stripe-node/issues/831). From what I see they don't plan on supporting any version except the latest version? I'd imagine the only way to get around that would be to use the Stripe node version which uses the API version that you want to use? 

My library lets you bring your own Stripe version at least... hopefully that helps a little bit. As long as you use `^8.0.0` you're good.

I do understand their reasoning though: kind of hard to maintain definitions for all of their API versions. Not ideal though.

**Comment by dhaspden** [comment]
Going to close this for now. Sorry I can't be of any more help! If they ever support this option we can revisit.
