### ISSUE TITLE
Adding the module in async mode not working

### ISSUE THREAD

**Issue by amanpreet-dev** [dhaspden/nestjs-stripe#93]
### Bug reports:

Facing issue while adding the module in Async mode
##

```
import { StripeModule } from 'nestjs-stripe';
import { ConfigModule, ConfigService } from '@nestjs/config';

imports:[
StripeModule.forRootAsync({
      useFactory: (configService: ConfigService) => ({
        apiKey:  configService.get('stripe_key'),
      }),
    }),]
```

Error coming 
`Type '(configService: ConfigService) => { apiKey: string; }' is not assignable to type '(...args: any[]) => StripeOptions | Promise<StripeOptions>'.
  Type '{ apiKey: string; }' is not assignable to type 'StripeOptions | Promise<StripeOptions>'.
    Property 'apiVersion' is missing in type '{ apiKey: string; }' but required in type 'StripeOptions'.`

## 
NEST JS v7

**Comment by nivBlox** [comment]
Hey, you are missing the apiVersion prop..

`imports: [
    _StripeModule.forRootAsync({
      inject: [ConfigService],
      useFactory: (configService: ConfigService) => ({
        apiKey: configService.get('STRIPE_KEY'),
        apiVersion: '2020-03-02',
      }),
    }),
  ],`


*** you can pass null if you wish to use default

**Comment by dhaspden** [comment]
Hey @amanpreet-dev thanks for the feedback. I was under the impression that the API version is defaulted if not supplied. I would like the API version to not have to be supplied. For now pass an API version and in the next release I'll see what I can do.

**Comment by dhaspden** [comment]
Collapsing this with #94. Thanks for the issue!
