### ISSUE TITLE
Property 'apiVersion' is missing in type '{ apiKey: string; }' but required in type 'StripeOptions'

### ISSUE THREAD

**Issue by dirk-jacobs** [dhaspden/nestjs-stripe#94]
When compiling, I receive the error mentioned in the subject.

Stripe version: "stripe": "^8.53.0"

interface StripeOptions extends Stripe.StripeConfig
apiVersion is the only mandatory parameter.

**Comment by shamoons** [comment]
Same issue

**Comment by osamahafez** [comment]
Same issue

**Comment by dyllanwli** [comment]
It seems the stripe v8.0.0 made some chanages. Check this https://github.com/stripe/stripe-node/pull/736.

**Comment by ChangSeopOh** [comment]
```
   useFactory: (config: ConfigService) => ({
        apiVersion: '2020-03-02',
        apiKey: config.get('STRIPE_SECRET_KEY'),
      }),
```
Add the apiVersion

**Comment by dhaspden** [comment]
Hi everyone, sorry about the delay.

I will update the documentation to reflect that the parameter is required. When using Typescript with the new Stripe library I am fairly confident you have to use the latest version of the API that corresponds to the version of the Stripe library you're using.

I'll update the example to reflect that this field is required. Thanks for bringing this up!

**Comment by dhaspden** [comment]
Thanks everyone, I've added a note in d0669404a6dc46bb8fef36632ca6e0215a86603f. This should solve your issues. Sorry for the confusion!
